version: "3.2"

services:
  angular:
    build:
      context: ./angular
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./angular/:/sources/
    ports:
      - 80:4200

  nestjs:
    build:
      context: ./nestjs
      dockerfile: Dockerfile
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo:27017/auth
    volumes:
      - ./nestjs/:/sources/
    depends_on:
      - mongo
    ports:
      - 3000:3000
      - 9229:9229
  
  mongo:
    image: mongo:3.6
    restart: always
    volumes:
      - ./mongo/db:/data/db
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo